name: Python Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run tests
        run: uv run pytest

      - name: Success message
        if: success()
        run: echo "Tests passed successfully!"
